project:
  type: website

website:
  title: "Jiping Li"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - href: work.qmd
        text: Work
      - href: about.qmd
        text: Other

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


