---
title: Experiences
toc: false
---

## 1. Instructor at [Ardent Academy](https://www.ardentacademy.com/) 

I enjoy helping other students learn mathematical concepts and perceive the beauty of this subject. During my work at Ardent Academy for the Gifted Youth in Irvine, California, I have served as an Instructor, Tutor, and Teaching Assistant since October 2022. My role involved leading three intensive AMC Bootcamps, where I guided students in enhancing their problem-solving skills at the competition math level. Additionally, I conducted weekly private sessions with students, providing personalized instruction across various subjects including AP Calculus BC, Pre-Calculus, AP Physics, AMC 12, and AIME. As a teaching assistant, I supported students in navigating challenging concepts and fostering a deeper understanding of the material. 

## 2. Course Reader at [UCLA Math Department](https://ww3.math.ucla.edu/)

From October 2023 to December 2023, I helped the grading process of weekly assessments for course Math 31B. 